### ISSUE TITLE
Fails to use the interface in a local instance

### ISSUE THREAD

**Issue by moissinac** [AngryLoki/wikidata-graph-builder#6]
Hello
I'm very interested by your tool, to illustrate some parts of my work
I've installed your tool on my PC. All seems OK
If I go to the pages with the following link
http://localhost:3000/?property=P279&item=Q33506
all is OK and similar to the online demo
But when I enter the text 'museum' in Root Item text box, I get 'No results'
Something seems to go wrong with the auto-completion
An idea?

**Comment by moissinac** [comment]
Something goes wrong with angular, as seen in the developper tools of my browser:
Request failed
(anonymous) @ angular.min.js:127
error @ all.min.js:801
(anonymous) @ angular.min.js:140
$digest @ angular.min.js:151
$apply @ angular.min.js:155
(anonymous) @ angular.min.js:22
invoke @ angular.min.js:45
c @ angular.min.js:22
Uc @ angular.min.js:22
Ae @ angular.min.js:21
(anonymous) @ angular.min.js:348
b @ angular.min.js:38
2angular.min.js:127 

ReferenceError: reject is not defined
    at error (all.min.js:802)
    at angular.min.js:140
    at m.$digest (angular.min.js:151)
    at m.$apply (angular.min.js:155)
    at angular.min.js:22
    at Object.invoke (angular.min.js:45)
    at c (angular.min.js:22)
    at Uc (angular.min.js:22)
    at Ae (angular.min.js:21)
    at angular.min.js:348 "Possibly unhandled rejection: {}"

**Comment by AngryLoki** [comment]
I suppose this is not a problem anymore, as it does not use angular anymore.
